name: tuned
description: A Tunedbass flutter starter template
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  flutter_hooks: ^0.20.3
  google_fonts: ^6.1.0
  #tu:
  #  path: /home/tonni/Documents/GitHub/flutter/tu
  tu:
    git:
      url: https://github.com/tonnidiaz/flutter_tu.git
      ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
