name: frust
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  ffi: ^2.0.2
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.79.0
  freezed_annotation: ^2.4.1
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  window_manager: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^8.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1

flutter:
  uses-material-design: true
